### ISSUE TITLE
bug：在使用Minecraft适配器时出现错误

### ISSUE THREAD

**Issue by MingriLingran** [17TheWord/nonebot-adapter-minecraft#19]
## 问题描述
在加载Minecraft适配器时pydantic出现问题

## 问题截图
![image](https://github.com/17TheWord/nonebot-adapter-minecraft/assets/99112592/aad78988-2670-4137-9f3d-dc1f0d313ed0)

其详细信息，我已在[nonebot2 issues提出](https://github.com/nonebot/nonebot2/issues/2588)

**Comment by 17TheWord** [comment]
暂未更新pydantic，可以先自行降级或魔改

**Comment by 17TheWord** [comment]
已在 [`v1.0.8.post1`](https://github.com/17TheWord/nonebot-adapter-minecraft/releases/tag/v1.0.8.post1) 支持 `Pydantic V2`
