### ISSUE TITLE
unicode的一些问题

### ISSUE THREAD

**Issue by yjcxgjmtd** [17TheWord/nonebot-adapter-minecraft#39]
使用mcqq互联

确认onebot v11和minecraft适配器都已安装

连接成功时，机器人输出了一个unicode的字符

![Image_1718983175615](https://github.com/17TheWord/nonebot-adapter-minecraft/assets/104567006/ab641b4b-d565-4c2c-97d2-15ad8e8f74fe)

请问如何解决这个问题！
我们尝试过更换locale，依旧没有用
操作环境：Linux系统、Python3.11.1

**Comment by 17TheWord** [comment]
给出你实用的所有组件的版本号，或者降低至2.65. 2.7.0进行尝试

**Comment by yjcxgjmtd** [comment]
已解决，将minecraft适配器降级到1.2.0就行了，
pyproject.toml需要加上    { name = "Minecraft", module_name = "nonebot.adapters.minecraft" }
**### 希望尽快适配新版本**

**Comment by 17TheWord** [comment]
> 已解决，将minecraft适配器降级到1.2.0就行了，
> pyproject.toml需要加上    { name = "Minecraft", module_name = "nonebot.adapters.minecraft" }
> **### 希望尽快适配新版本**

新版更新了服务器名的转码方式，要么提高你的mc组件版本，要么降低你的适配器版本，无需适配
