### ISSUE TITLE
Spigot无法建立连接

### ISSUE THREAD

**Issue by XiYang6666** [17TheWord/nonebot-adapter-minecraft#4]
MC服务器显示: "[MC_QQ] WebSocket 连接已断开,正在第 xx 次重新连接。"
Nonebot显示:
08-29 22:26:36 [INFO] uvicorn | ('192.168.21.25', 40550) - "WebSocket /spigot/ws" 403
08-29 22:26:36 [INFO] websockets | connection failed (403 Forbidden)
08-29 22:26:36 [INFO] websockets | connection closed

**Comment by 17TheWord** [comment]
> MC服务器显示: "[MC_QQ] WebSocket 连接已断开,正在第 xx 次重新连接。" Nonebot显示: 08-29 22:26:36 [INFO] uvicorn | ('192.168.21.25', 40550) - "WebSocket /spigot/ws" 403 08-29 22:26:36 [INFO] websockets | connection failed (403 Forbidden) 08-29 22:26:36 [INFO] websockets | connection closed

`/spigot/ws` 改为 `/minecraft/ws`，可能是我文档没及时更新，你是在哪边看的，我去更新下描述

**Comment by XiYang6666** [comment]
> > MC服务器显示: "[MC_QQ] WebSocket 连接已断开,正在第 xx 次重新连接。" Nonebot显示: 08-29 22:26:36 [INFO] uvicorn | ('192.168.21.25', 40550) - "WebSocket /spigot/ws" 403 08-29 22:26:36 [INFO] websockets | connection failed (403 Forbidden) 08-29 22:26:36 [INFO] websockets | connection closed
> 
> `/spigot/ws` 改为 `/minecraft/ws`，可能是我文档没及时更新，你是在哪边看的，我去更新下描述

在spigot插件默认配置的注释中

**Comment by 17TheWord** [comment]
> > > MC服务器显示: "[MC_QQ] WebSocket 连接已断开,正在第 xx 次重新连接。" Nonebot显示: 08-29 22:26:36 [INFO] uvicorn | ('192.168.21.25', 40550) - "WebSocket /spigot/ws" 403 08-29 22:26:36 [INFO] websockets | connection failed (403 Forbidden) 08-29 22:26:36 [INFO] websockets | connection closed
> > 
> > 
> > `/spigot/ws` 改为 `/minecraft/ws`，可能是我文档没及时更新，你是在哪边看的，我去更新下描述
> 
> 在spigot插件默认配置的注释中

很久没写了，看来需要更新一波

**Comment by 17TheWord** [comment]
完整的链接应该是这样的
```yaml
websocket_url: "ws://127.0.0.1:8080/onebot/v11/mcqq"
```
